import { MetadataRoute } from 'next'

const BASE_URL = 'https://docs.connectonion.com'

const pages: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'] }[] = [
  { path: '/', priority: 1.0, changeFrequency: 'daily' },
  { path: '/quickstart', priority: 0.9, changeFrequency: 'weekly' },
  { path: '/vibe-coding', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/cli', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/cli/ai', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/cli/browser-command', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/cli/copy', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/agent', priority: 0.9, changeFrequency: 'weekly' },
  { path: '/tools', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/tools/browser', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/models', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/models/pricing', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/prompts', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/prompts/formats', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/prompts/examples', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/llm_do', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/on_events', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/plugin', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/logging', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/memory', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/host', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/connect', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/deploy', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/session-reconnect', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/websocket-protocol', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/threat-model', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/features/permissions', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/features/skills', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/features/transcribe', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/features/trust', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/useful-tools', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/useful-tools/codex', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/bash', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/shell', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/diff-writer', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/file-tools', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/browser-tools', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/slash-command', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/terminal', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-tools/todo-list', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/web-fetch', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/agent-emails', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/agent-emails/send', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/agent-emails/receive', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/gmail', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/outlook', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/google-integration', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/microsoft-integration', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/useful-plugins/re-act', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/eval', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/image-result-formatter', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/shell-approval', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/gmail-plugin', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/calendar-plugin', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/system-reminder', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/prefer-write-tool', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/skills', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-skills', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/useful-skills/ship-feature', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/tool-approval', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/auto-compact', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/subagents', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/useful-plugins/ulw', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/useful-plugins/ui-stream', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/auto-debug', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/auto-debug-exception', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/xray', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/xray/trace', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/tui/pick', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/input', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/dropdown', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/status-bar', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/footer', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/divider', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/fuzzy', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/keys', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/providers', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/tui/chat', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/examples', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/examples/calculator', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/examples/browser', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/prompts/examples/math-tutor', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/technical-writer', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/code-reviewer', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/business-strategist', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/friendly-assistant', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/data-analyst', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/security-analyst', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/prompts/examples/customer-support', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/blog/oip-native-coding-adapters', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/blog/agent-address-format', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/auto-debug-evolution', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/cli-ux-progressive-disclosure', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/input-method', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/llm-do', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/naming-is-hard', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/network-protocol-design', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog/trust-keyword', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/links', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/roadmap', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/website-maintenance', priority: 0.3, changeFrequency: 'monthly' },
]

export default function sitemap(): MetadataRoute.Sitemap {
  return pages.map(({ path, priority, changeFrequency }) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }))
}
